"""empty message

Revision ID: 144755c652bb
Revises: d731d8542c74
Create Date: 2025-03-14 09:42:17.013580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144755c652bb'
down_revision = 'd731d8542c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profiles', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###
